
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: case-study
  name: case-study-deployment
spec:
  selector:
    matchLabels:
      run: case-study-server
  template:
    metadata:
      labels:
        run: case-study-server
    spec:
      containers:
        - name: case-study-server
          image: 'case-study-server:2025-10-09'
          ports:
            - containerPort: 10201
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: case-study
  name: case-study-service
spec:
  type: NodePort
  ports:
    - port: 10201
  selector:
    run: case-study-server
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: case-study
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: the-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100      # Scale up by max 100% of current replicas
          periodSeconds: 10
    scaleDown:
      stabilizationWindowSeconds: 30  # Default is 300s (5 min)
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
