
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: case-study
  name: case-study-deployment
spec:
  selector:
    matchLabels:
      run: case-study-server
  template:
    metadata:
      labels:
        run: case-study-server
    spec:
      containers:
        - name: case-study-server
          image: 'case-study-server:2025-10-09'
          ports:
            - containerPort: 10201
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: case-study
  name: case-study-service
spec:
  type: NodePort
  ports:
    - port: 10201
  selector:
    run: case-study-server
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: auto-scaler
  namespace: case-study
spec:
  scaleTargetRef:
    name: case-study-deployment
  minReplicaCount: 1
  maxReplicaCount: 20
  pollingInterval: 5
  cooldownPeriod: 5
  triggers:
    - type: metrics-api
      metadata:
        activationTargetValue: "0.5"
        targetValue: "1"
        url: "http://case-study-service.case-study.svc.cluster.local:10201/metrics/rps"
        valueLocation: "requestsPerSecond"