
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: case-study
  name: case-study-deployment
spec:
  selector:
    matchLabels:
      run: case-study-server
  template:
    metadata:
      labels:
        run: case-study-server
    spec:
      containers:
        - name: case-study-server
          image: 'case-study-server:2025-10-09'
          ports:
            - containerPort: 10201
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: case-study
  name: case-study-service
spec:
  type: NodePort
  ports:
    - port: 10201
  selector:
    run: case-study-server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: case-study
data:
  rules.yaml: |
    rules:
      - seriesQuery: 'custom_metric'
        resources:
          overrides:
            namespace: {resource: "namespace"}
            pod: {resource: "pod"}
        name:
          matches: "^(.*)"
          as: "${1}"
        metricsQuery: '${metric}'
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: case-study
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: case-study-deployment
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: "1"  # scale up if avg > 1 req/s per pod